### ISSUE TITLE
Import Assertions do not work in Firefox

### ISSUE THREAD

**Issue by sinistersnare** [gerusz/dm_loading_screen#1]
Hi, this project uses a v8 feature [import assertions](https://v8.dev/features/import-assertions), which are not supported in non-chromium browsers AFAIK.

Just wanted to state that if you were unaware of your FF incompatibility!

**Comment by sinistersnare** [comment]
I hacked around it locally by replacing the imports with:

```
function get(where) {
    return fetch(where)
        .then((response) => response.json())
        .then((json) => json);
}
const hints = await get('./hints.json');
const images = await get('./images.json');
const config = await get('./config.json');
```

**Comment by gerusz** [comment]
Hi! Yes, I'm aware and I think I fixed that specific issue. Still can't get it to work reliably in FF, but I'm working on it.

**Comment by gerusz** [comment]
Update: seems to be working? Needs a lot more beta testers to see if it is actually fixed or I just lucked out, but "It Works On My Computer"™. I'll close the issue for now.

**Comment by sinistersnare** [comment]
Seems to be working great for me. Thanks!
